# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/g3-common/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
<<<<<<< HEAD:g3-common/g3-common-vendor.mk
PRODUCT_PACKAGES += \
    com.qualcomm.location \
    com.qualcomm.services.location \
    TimeService \
    qcrilmsgtunnel \
    shutdownlistener \
    qcnvitems \
    qcrilhook \
    libHevcSwDecoder \
    libtime_genoff
=======
>>>>>>> 664eee8... initial support for LG Leon:ms345/ms345-vendor.mk

$(call inherit-product, vendor/lge/g3-common/g3-common-vendor-blobs.mk)
